// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'newTodoButton': string;
  'newTodoForm': string;
  'newTodoInput': string;
}
export const cssExports: CssExports;
export default cssExports;
