// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonContainer': string;
  'completedButton': string;
  'removeButton': string;
  'todoItemContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
